{"name": "Тест удаления курьера с несуществующим id", "status": "passed", "description": "Если отправить запрос с несуществующим id, вернётся ошибка Not Found", "steps": [{"name": "Отправляем запрос на удаление курьера", "status": "passed", "parameters": [{"name": "courier_id", "value": "6797697"}], "start": 1715023357044, "stop": 1715023357682}], "start": 1715023357043, "stop": 1715023357685, "uuid": "89ddbfc9-882f-400a-9d2f-f243d0c6e97e", "historyId": "e6981f30ed8e5deb000d994610c86235", "testCaseId": "e6981f30ed8e5deb000d994610c86235", "fullName": "tests.test_courier_delete.TestCourierDelete#test_delete_courier_wrong_id_return_not_found_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_delete"}, {"name": "subSuite", "value": "TestCourierDelete"}, {"name": "host", "value": "DESKTOP-9PI1IG9"}, {"name": "thread", "value": "9108-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_delete"}]}