{"name": "Тест удаления курьера без указания id", "status": "passed", "description": "Если отправить запрос без id, вернётся ошибка Not Found", "steps": [{"name": "Отправляем запрос на удаление курьера", "status": "passed", "parameters": [{"name": "courier_id", "value": "''"}], "start": 1715023356400, "stop": 1715023357037}], "start": 1715023356400, "stop": 1715023357040, "uuid": "8b839969-0ffb-4630-a897-01916eb03cea", "historyId": "d187dffb658c077a6452892c57c2b58f", "testCaseId": "d187dffb658c077a6452892c57c2b58f", "fullName": "tests.test_courier_delete.TestCourierDelete#test_delete_courier_without_id_return_not_found_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_delete"}, {"name": "subSuite", "value": "TestCourierDelete"}, {"name": "host", "value": "DESKTOP-9PI1IG9"}, {"name": "thread", "value": "9108-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_delete"}]}