{"name": "Тест принятия заказа с неверным id курьера/заказа", "status": "passed", "description": "Если передать неверный id курьера/заказа, запрос вернёт ошибку Not Found", "steps": [{"name": "Отправляем запрос на принятие заказа", "status": "passed", "parameters": [{"name": "order_id", "value": "3175195"}, {"name": "courier_id", "value": "301402"}], "start": 1715023383085, "stop": 1715023384341}, {"name": "Отправляем запрос на авторизацию курьера", "status": "passed", "parameters": [{"name": "payload", "value": "{'login': 'copigikcil', 'password': 'daotgzwnct'}"}], "start": 1715023384341, "stop": 1715023384991}, {"name": "Отправляем запрос на удаление курьера", "status": "passed", "parameters": [{"name": "courier_id", "value": "301402"}], "start": 1715023384991, "stop": 1715023385649}], "parameters": [{"name": "parameter_number", "value": "0"}], "start": 1715023383084, "stop": 1715023385655, "uuid": "fb36034c-2d64-452b-8033-03fc55b03291", "historyId": "cb04a8d420e6067ac79837923a2c3cc8", "testCaseId": "469674aa16559dae50bc69cfbf16945a", "fullName": "tests.test_orders_accept.TestOrdersAccept#test_accept_order_wrong_id_return_not_found_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_orders_accept"}, {"name": "subSuite", "value": "TestOrdersAccept"}, {"name": "host", "value": "DESKTOP-9PI1IG9"}, {"name": "thread", "value": "9108-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_orders_accept"}]}